// scripts/update-server.ts

import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

const TOOLS_DIR = path.join(ROOT, "src", "tools");
const SERVER_FILE = path.join(ROOT, "src", "server.ts");

type ToolModule = {
  name: string;
  importPath: string;
  registerFn: string;
};

async function exists(file: string): Promise<boolean> {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}

function capitalize(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

async function discoverTools(): Promise<ToolModule[]> {
  const entries = await fs.readdir(TOOLS_DIR, {
    withFileTypes: true,
  });

  const tools: ToolModule[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const indexFile = path.join(TOOLS_DIR, entry.name, "index.ts");

    if (!(await exists(indexFile))) continue;

    const name = capitalize(entry.name);

    tools.push({
      name: entry.name,
      importPath: `./tools/${entry.name}`,
      registerFn: `register${name}Tools`,
    });
  }

  return tools.sort((a, b) => a.name.localeCompare(b.name));
}

function generateImports(tools: ToolModule[]) {
  return tools
    .map(
      (tool) =>
        `import { ${tool.registerFn} } from "${tool.importPath}";`,
    )
    .join("\n");
}

function generateRegistrations(tools: ToolModule[]) {
  return tools
    .map((tool) => `${tool.registerFn}(server.tools);`)
    .join("\n\n");
}

function generateServer(tools: ToolModule[]): string {
  return `import type { ToolRegistry } from "./contracts/tool";

${generateImports(tools)}

export type Env = {
  STATE_KV: KVNamespace;

  API_KEY?: string;

  GITHUB_OWNER?: string;

  GITHUB_REPO?: string;

  GITHUB_BRANCH?: string;

  GITHUB_TOKEN?: string;
};

export const server: {
  tools: ToolRegistry<Env>;
} = {
  tools: {},
};

/*
 * ------------------------------------------------------------------
 * THIS FILE IS AUTO-GENERATED.
 *
 * Generated by:
 *   scripts/update-server.ts
 *
 * DO NOT EDIT MANUALLY.
 * ------------------------------------------------------------------
 */

${generateRegistrations(tools)}
`;
}

async function main() {
  const tools = await discoverTools();

  console.log("");

  console.log("Discovered tools:");

  for (const tool of tools) {
    console.log(`  • ${tool.name}`);
  }

  console.log("");

  const content = generateServer(tools);

  await fs.writeFile(SERVER_FILE, content, "utf8");

  console.log(`Generated ${path.relative(ROOT, SERVER_FILE)}`);

  console.log(`Registered ${tools.length} tool modules.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});